### ISSUE TITLE
CLI can segfault in `tap`

### ISSUE THREAD

**Issue by olix0r** [runconduit/conduit#295] opened 2018-02-08 01:04 UTC
Running against a remote K8s cluster, running the following for several minutes (including closing/opening my laptop).
```
:; conduit tap deploy emojivoto/voting-svc --path /emojivoto.v1.VotingService/VotePoop                        
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x186b213]

goroutine 1 [running]:
github.com/runconduit/conduit/cli/cmd.renderTapEvent(0xc4201c23a0, 0xc4201c23a0, 0x0)
    /go/src/github.com/runconduit/conduit/cli/cmd/tap.go:149 +0x1b3
github.com/runconduit/conduit/cli/cmd.writeTapEventsToBuffer(0x20b8a40, 0xc4204e73c0, 0xc4201d2100, 0x0, 0x0)
    /go/src/github.com/runconduit/conduit/cli/cmd/tap.go:133 +0xca
github.com/runconduit/conduit/cli/cmd.renderTap(0x20a4ca0, 0xc42000c018, 0x20b8a40, 0xc4204e73c0, 0x0, 0x0)
    /go/src/github.com/runconduit/conduit/cli/cmd/tap.go:113 +0x89
github.com/runconduit/conduit/cli/cmd.requestTapFromApi(0x20a4ca0, 0xc42000c018, 0x20b62e0, 0xc42034c310, 0x7ffeefbff943, 0x14, 0x1ace1a9, 0xb, 0xc42033a680, 0x1b37ec8, ...)
    /go/src/github.com/runconduit/conduit/cli/cmd/tap.go:108 +0x24b
github.com/runconduit/conduit/cli/cmd.glob..func9(0x2103440, 0xc420328600, 0x2, 0x4, 0x0, 0x0)
    /go/src/github.com/runconduit/conduit/cli/cmd/tap.go:70 +0x2e1
github.com/runconduit/conduit/vendor/github.com/spf13/cobra.(*Command).execute(0x2103440, 0xc420328580, 0x4, 0x4, 0x2103440, 0xc420328580)
    /go/src/github.com/runconduit/conduit/vendor/github.com/spf13/cobra/command.go:698 +0x47a
github.com/runconduit/conduit/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x2102560, 0xc4204cbf40, 0x18d2001, 0xc4204cbf50)
    /go/src/github.com/runconduit/conduit/vendor/github.com/spf13/cobra/command.go:783 +0x30e
github.com/runconduit/conduit/vendor/github.com/spf13/cobra.(*Command).Execute(0x2102560, 0xc4204cbf70, 0x18d3d9e)
    /go/src/github.com/runconduit/conduit/vendor/github.com/spf13/cobra/command.go:736 +0x2b
main.main()
    /go/src/github.com/runconduit/conduit/cli/main.go:12 +0x2d```

**Comment by klingerf** [comment] 2018-02-13 19:53
Closing this as a duplicate of #47.

**Closed by klingerf** 2018-02-13 19:53 UTC
Labels: bug, cli
