### ISSUE TITLE
Proxy intermittently fails to route traffic when --skip-inbound-ports is not set

### ISSUE THREAD

**Issue by deebo91** [runconduit/conduit#211] opened 2018-01-26 00:10 UTC
When working through the `BUILD.md`. We encounter an error were we cannot access the `emojivoto web-svc` on minikube. The issue occurs after we run `curl https://raw.githubusercontent.com/runconduit/conduit-examples/master/emojivoto/emojivoto.yml | target/cli/darwin/conduit inject - | kubectl apply -f -` without the `--skip-inbound-ports` flag.

**Comment by klingerf** [comment] 2018-01-26 01:13
The fix for this is in #208.

**Comment by olix0r** [comment] 2018-01-26 01:14
Yes, this was user error and not a bug ;)

**Closed** 2018-01-26 19:43 UTC
Labels: proxy
