### ISSUE TITLE
[documentation] Add Redis to the TCP traffic that needs to be excluded

### ISSUE THREAD

**Issue by bourquep** [runconduit/conduit#432] opened 2018-02-23 04:10 UTC
[This page](https://conduit.io/adding-your-service/#protocol-support) mentions MySQL and SMTP as examples of TCP protocols which aren't properly handled by Conduit.

It would be worth adding Redis to this list, as it too needs to be excluded from Conduit proxied ports.

**Comment by briansmith** [comment] 2018-02-26 23:52
Is Redis a server-speaks-first protocol like MySQL and SMTP? If so, then we already know the most-likely cause of this and we should just update the documentation for 0.3.1. Our goal is to make this kind of configuration unnecessary for server-speaks-first protocols in 0.4; see #339.

If, however, the Redis protocol isn't a server-speaks-first protocol then this is a different problem and we need to do some debugging to find out what Redis isn't working transparently already.

**Comment by deebo91** [comment] 2018-02-27 01:12
I think we may have to do debugging to verify what redis actually does when it first gets in contact with a peer. According to https://redis.io/topics/protocol, Redis is generally a request-response protocol, meaning that the client sends packets first. However, you could use redis in Pub/Sub model and this may be an issue that a proxy that might run into. Check out this quote from their documentation.

> When a Redis client subscribes to a Pub/Sub channel, the protocol changes semantics and becomes a push protocol, that is, the client no longer requires to send commands, because the server will automatically send to the client new messages (for the channels the client is subscribed to) as soon as they are received.

This sounds like this may be a __server-speaks-first__ protocol. But we can't be certain until we have a good test to confirm that.

**Comment by deebo91** [comment] 2018-02-27 01:26
UPDATE: Working with @pcalcado to see if we can come to any definite conclusions about Redis through some tests possibly tomorrow.

**Comment by deebo91** [comment] 2018-02-28 00:28
After running a few tests, we have seen that conduit transparently routes requests through a redis deployment using both Pub/Sub and Request-Response communication patterns. The caveat is that we do not record telemetry for raw TCP which makes it difficult to observe how traffic is flowing through a Redis instance. @bourquep I am curious to know what you see when you inject conduit into a redis environment. Do requests that are targeted for redis hang indefinitely?

**Comment by bourquep** [comment] 2018-02-28 01:51
@deebo91 What triggered this for me is I started seeing a ton of _connection refused_ errors in my NodeJS service that uses Redis, shortly after injecting conduit into that deployment. I immediately reinjected with Redis port skipped, but did not do any further forensics unfortunately. 

It might have been a side effect of the TCP port leaks (see other issue for which I don’t have the number at hand). I’ll check my Redis logs to see if the number of active connections skyrocketed on that specific date and time. 

![11901724-f8ec-4986-b606-6f538bd7191f](https://user-images.githubusercontent.com/65096/36765585-e3f17988-1bff-11e8-9ad9-5690c809cec6.jpeg)

**Comment by bourquep** [comment] 2018-02-28 02:00
Nope, no spike in Redis connections when I saw this error spike. 

Could it be related to the fact that my Redis server is running outside of the k8s cluster and accessed by DNS name?

Anyhow, I had never had this connection error before injecting Conduit, and it went away after skipping the Redis port.

**Comment by briansmith** [comment] 2018-02-28 02:04
> Could it be related to the fact that my Redis server is running outside of the k8s cluster and accessed by DNS name?

1. How many labels does the DNS name have? e.g. "example.com" has two labels, "www.example.com" has three labels, and "foo.bar.example.com" has four labels. If the service had less than two labels in its DNS name, could you try one that has at least 3?

2. By "accessed by a DNS name" do you mean that  you did NOT create an Kubernetes service with type = ExternalName for it?

**Comment by bourquep** [comment] 2018-02-28 03:14
>How many labels does the DNS name have?

It has 4 labels.

>By "accessed by a DNS name" do you mean that you did NOT create an Kubernetes service with type = ExternalName for it?

Exactly, no k8s service involved. Should I try that?

**Comment by briansmith** [comment] 2018-02-28 03:18
> Exactly, no k8s service involved. Should I try that?

No, ExternalName services won't be supported until #155 is fully fixed. Similarly, if there were only 1 or 2 labels then that isn't expected to work either. However, the configuration you gave should already be working, w.r.t. the being able to contact things outside the cluster.

**Comment by dadjeibaah** [comment] 2018-03-02 19:03
> However, the configuration you gave should already be working, w.r.t. the being able to contact things outside the cluster.

@briansmith does your comment above suggest that this is a bug not related to #155? We could run tests by having an external redis client and try to communicate from a proxy-enabled client from within k8s.

**Comment by briansmith** [comment] 2018-03-02 19:09
@dadjeibaah At this point I don't think we can blame #155 for this.

I feel like we don't really know what's going on here. It's very possible that this *is* something Redis-specific but based on @dadjeibaah's testing we can't reproduce it, so it apparently doesn't affect *all* redis deployments, so I don't think we should just slap a "disable the proxy for Redis" into the docs just yet. We need to find STR.

@bourquep Which version of Redis are you using? Which software was the client and which software was the server? Thanks!

**Comment by dadjeibaah** [comment] 2018-03-02 19:20
Since we designed the test to accept any redis server, whether it be external or internal to k8s, it is pretty easy to setup a test with an external redis server. I can set that up and see what I find.

**Comment by briansmith** [comment] 2018-03-02 19:21
FWIW, I looked at https://redis.io/topics/protocol and it doesn't appear to be a server-speaks-first protocol. I did notice that the messages that the client sends to the server might be small. That reminded me of https://github.com/runconduit/conduit/pull/231 (thanks for the link, @seanmonstar). Thus, the issue might be an issue in our protocol-detection logic: maybe we're too eager to assume a connection is an HTTP connection when really it might be a Redis connection.

**Comment by briansmith** [comment] 2018-03-02 19:24
Let's write a unit test in the proxy where we attempt to send (outbound) the minimal Redis message that a Redis client might send at the beginning of a connection, and see if the protocol detection logic (etc.) is doing the right thing.

**Comment by bourquep** [comment] 2018-03-02 20:08
@briansmith:

>Which version of Redis are you using? Which software was the client and which software was the server?

* Server: Redis v3.0.6 (one instance, no replication)
* Client: ioredis v2.4.0 (npm package) running on NodeJS v6

Also, and I am terribly sorry for having misreported this earlier, we are not accessing the Redis server via DNS name but rather via it's internal Google Compute Engine IP address (`redis://10.x.0.x`). We used to access it via DNS name but changed the connection string to point to its internal IP later on, and I had completely forgotten about that. 😩

**Comment by briansmith** [comment] 2018-03-02 20:47
@bourquep Thanks for those additional details!

**Comment by briansmith** [comment] 2018-03-06 20:12
@bourquep Thanks again for the additional details. I think what we need to do now is try to reproduce specifically with ioredis. In particular, it seems like if ioredis is using the normal Redis protocol then Conduit's protocol detection logic shouldn't confuse it with HTTP traffic, and so any problem you experienced wouldn't be related to protocol detection. However, if it is using the human-oriented form of the Redis protocol then it *might* be confusing it with HTTP traffic, because the human-oriented form of the Redis protocol does look quite a bit like HTTP. So we should try to find a tcpdump from ioredis 2.4.0 connecting to a Redis server to make progress.

**Comment by seanmonstar** [comment] 2018-03-06 20:47
Something we could also do is add a trace log of the bytes when protocol detection completes, to allow debugging.

A downside is whether there is concern of dumping possibly sensitive bytes into the logs.

**Comment by dadjeibaah** [comment] 2018-03-06 22:16
I can also setup a NodeJS client that talks to Redis. I currently have a test environment but the client is in go. I can try seeing if I can get tcdumps in my test env.

**Comment by seanmonstar** [comment] 2018-03-16 22:58
Digging through the source of ioredis 2.4.0, it seems it is using a protocol that does not look like HTTP: https://github.com/luin/ioredis/blob/v2.4.0/lib/command.js#L146

That means commands look like:

```
*2
$4
LLEN
$6
mylist

```

The current protocol detector will notice it isn't the HTTP2 preface, and that `*2\r\n` is not a valid HTTP1 request line, and so should treat as opaque TCP.

**Comment by bourquep** [comment] 2018-03-16 23:02
Now that I have 0.3.1 running in prod, I can test this again in a more controlled manner. I'm skipping the Redis outbound port in all my proxy injections right now, but I'll let it go through the proxy for one of my deployments which accesses Redis and monitor the logs more closely.

I should be able to do that early next week.

**Comment by klingerf** [comment] 2018-05-29 23:17
Hey @bourquep, any update on testing your deployments that access Redis? I tested this with Conduit v0.4.1 and it seemed to work without requiring the `--skip-outbound-ports` flag.

**Comment by bourquep** [comment] 2018-05-29 23:18
Yes indeed, haven't had any problem with accessing Redis through Conduit since I-don't-remember-which-release. :)

**Comment by klingerf** [comment] 2018-05-29 23:19
@bourquep 🎉 🎉 🎉 Thanks! Am going to close this.

**Closed by klingerf** 2018-05-29 23:19 UTC
Labels: area/docs, priority/P1
