### ISSUE TITLE
Augment destination service responses with deployment information

### ISSUE THREAD

**Issue by adleong** [runconduit/conduit#429] opened 2018-02-23 00:11 UTC
Each TcpAddress returned by the Destination service should also include a list of Prometheus label-value pairs.  These label-value pairs are intended to be attached to all `outgoing` metrics about this address.

Each address should have a Prometheus label-value pair attached to it that represents its owner.  E.g. "job=bar" or "replicationcontroller=bas' etc.

This is required for the proxy to be able to set the `target_<Y>` label on outgoing traffic (#425).

**Comment by olix0r** [comment] 2018-03-04 21:38
Per #508, I don't think that this is sufficient.  We should aim to handle this generally so that we don't have to model all kubernetes pod resource parents in this API.  I think that we should support address metadata, including an arbitrary set of prometheus labels.

**Comment by adleong** [comment] 2018-03-04 22:53
I've updated the description to accommodate other potential Prometheus label-value pairs.

**Comment by olix0r** [comment] 2018-03-26 16:18
Note that some of the details have been updated in https://github.com/runconduit/conduit/blob/master/doc/proxy-metrics.md (and that's still not quite right).

The dst service should add per-endpoint `metric_labels`, including:

* `k8s_namespace`: Kubernetes namespace that the pod belongs to.
* `k8s_pod`: The name of the endpoint's pod.
* `k8s_job`: The replica set that the pod belongs to (if applicable).
* `k8s_replica_set`: The replica set that the pod belongs to (if applicable).
* `k8s_daemon_set`: The daemon set that the pod belongs to (if applicable).
* `k8s_replication_controller`: The replication controller that the pod belongs to (if applicable).
* `k8s_deployment`: The deployment that owns the pod's replicaset (if applicable).

The proxy is responsible for prefixing these keys with `dst_`

**Comment by olix0r** [comment] 2018-03-26 16:20
You could also potentially opt to extract common labels into the WeightedAddrSet response, (i.e. so that `k8s_namespace` & `k8s_service` need not be repeated).

**Comment by pcalcado** [comment] 2018-03-26 17:38
@olix0r so we need those keys to be typed, i.e. would maops like these work:

```protobuf

service Destination {
  // Given a destination, return all addresses in that destination as a long-
  // running stream of updates.
  rpc Get(common.Destination) returns (stream Update) {}
}

message Update {
  oneof update {
    WeightedAddrSet add = 1;
    AddrSet remove = 2;
  }
}

message AddrSet {
  repeated common.TcpAddress addrs = 1;
}

message WeightedAddrSet {
  repeated WeightedAddr addrs = 1;
  map<string, string> labels = 2;
}

message WeightedAddr {
  common.TcpAddress addr = 1;
  uint32 weight = 3;
  map<string, string> labels = 4;
}
```

Also, FYI I am working under the assumption that we shouldn't be changing/refactoring this proto much to avoid unnecessary churn on the proxy code, let me know if otherwise

/cc @hawkw

**Comment by olix0r** [comment] 2018-03-26 17:42
@pcalcado exactly what i was thinking!  I'd suggest calling the field `metric_labels`, as to be clear that these are not kubernetes labels.

**Comment by pcalcado** [comment] 2018-03-29 04:05
@adleong @olix0r I have a question here. Getting the metadata and adding it to the response is fairly easy after #645 , but the problem is that our destination service seems to work with _services_ not pods. i.e. a call to `Get` will return the IP for the service (load balancer, external name, or eventually cluster IP), which then redirects to pods.

As it stands, `inject` adds the metadata described above to _pods_, but not to _services_. The same is 
true for various labels described above, around ReplicaController, Job, Pods, and whatnot.

Is a requirement for this issue that we manually find which pods are acting as back-ends to a service and then find conduit metadata  + what ReplicationControllers, jobs, etc. that created them? Or maybe I am missing something here?

**Comment by adleong** [comment] 2018-03-29 07:36
@pcalcado `Get` takes a service and uses the Kubernetes endpoints API to resolve that to a set of addresses.  I imagine that the easiest way to implement this change is to have the destination service also watch the Kubernetes pods API and keep an index by pod ip so that the pod object can be looked up for each IP that we return and the pod owner can be extracted from the pod object and attached to the response.

I believe there is code that already does almost exactly this in the telemetry service that we should be able to crib from.  The telemetry service gets reports that contain IPs and must resolve those to pod and pod owner.

**Comment by olix0r** [comment] 2018-04-04 21:56
This is mostly resolved by https://github.com/runconduit/conduit/pull/654, though there are some followup issues like #655 and #668

**Closed by olix0r** 2018-04-04 21:56 UTC
Labels: area/controller, area/proxy, area/telemetry, priority/P0
