### ISSUE TITLE
Reintroduce path- and pod-oriented metrics

### ISSUE THREAD

**Issue by olix0r** [runconduit/conduit#405] opened 2018-02-21 18:45 UTC
We've temporarily removed path- and pod-oriented metrics to help manage cardinality.

We need to find a way to reintroduce these metrics without exploding the timeseries.

**Comment by adleong** [comment] 2018-03-03 08:00
Closing as a duplicate of #504 and yet-to-be scoped work coming in milestone 0.5.0

**Closed by adleong** 2018-03-03 08:00 UTC
Labels: telemetry
