### ISSUE TITLE
Conduit doesn't seem to work in IPv6

### ISSUE THREAD

**Issue by valentin2105** [runconduit/conduit#257] opened 2018-02-02 03:03 UTC
Hi,

I currently trying to make Conduit work in my IPv6-only cluster, and I face some problems, 

I have made some change on the .yaml file to disable 10.32.x. services and replace them to `ClusterIP: none` svc.

All the Conduit components run fine, without any error, 

When  I inject conduit in my deployment, change the cluster domain and the IPv6 binding on the injected .yaml and deploy it,  it isn't detected by Conduit himself ..

Here his the conduit-proxy logs for my deployment (basic nginx deployment) : 

```
1517540343.322389 DBUG tokio_core::reactor loop time - Instant { tv_sec: 14929, tv_nsec: 25991688 }
1517540343.322438 DBUG tokio_core::reactor::timeout_token cancel timeout 2
1517540343.322469 DBUG tokio_core::reactor cancel a timeout: 2
1517540343.322508 DBUG tokio_core::reactor scheduling direction for: 1
1517540343.322523 DBUG tokio_core::reactor blocking
1517540343.322540 DBUG tokio_core::reactor added a timeout: 2
1517540343.322575 DBUG tokio_core::reactor loop process - 1 events, Duration { secs: 0, nanos: 217251 }
1517540343.322598 DBUG tokio_core::reactor loop poll - Duration { secs: 0, nanos: 4148 }
1517540343.322611 DBUG tokio_core::reactor loop time - Instant { tv_sec: 14929, tv_nsec: 26231606 }
1517540343.322632 DBUG tokio_core::reactor::timeout_token "controller-client", cancel timeout 5
1517540343.322643 DBUG tokio_core::reactor "controller-client", cancel a timeout: 5
1517540343.322657 WARN conduit_proxy::control "controller-client", controller error: Connect(Connect(Error(Error { repr: Custom(Custom { kind: NotFound, error: StringError("DNS resolution failed") }) })))
1517540343.322691 DBUG tokio_core::reactor "controller-client", set a timeout: 1
1517540343.322711 DBUG tokio_core::reactor "controller-client", updating a timeout: 1
1517540343.322730 DBUG tokio_core::reactor "controller-client", updating a timeout: 0
1517540343.322746 DBUG tokio_core::reactor "controller-client", scheduling direction for: 0
1517540343.322756 DBUG tokio_core::reactor "controller-client", blocking
1517540343.322803 DBUG tokio_core::reactor loop process - 1 events, Duration { secs: 0, nanos: 204706 }
1517540343.322824 DBUG tokio_core::reactor loop poll - Duration { secs: 0, nanos: 3561 }
1517540343.322838 DBUG tokio_core::reactor loop time - Instant { tv_sec: 14929, tv_nsec: 26458238 }
1517540343.322848 DBUG tokio_core::reactor loop process - 0 events, Duration { secs: 0, nanos: 24378 }

```
`{ kind: NotFound, error: StringError("DNS resolution failed") }) })))`

Thanks

**Comment by briansmith** [comment] 2018-02-02 07:51
Thanks for the bug report. I'm going to close this as a duplicate of #91 as I think they are the same issue. I will follow up with a comment in #91.

**Closed** 2018-02-02 07:51 UTC
